name: lecsens
description: "Detektor cemaran pada air yang portable, mudah digunakan, cepat, dan akurat."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  date_picker_timeline: ^1.2.6
  syncfusion_flutter_charts: ^26.2.5+1
  provider: ^6.0.0
  url_launcher: ^6.0.9
  sqflite: ^2.3.3+1
  path: ^1.9.0
  http: ^0.13.5
  shared_preferences: ^2.0.18
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - lib/res/images/lecsens_logo.png
    - lib/res/images/ambil_data.png
    - lib/res/images/alat.png
    - lib/res/images/arsen.png
    - lib/res/images/kadmium.png
    - lib/res/images/merkuri.png
    - lib/res/images/microplastics.png
    - lib/res/images/timbal.png
    